### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by adenta** [homanp/langchain-ui#96]
So I have a bunch of chat transcripts as text files. Looks like I need to convert these chat transcripts into a CSV. What should the CSV look like?

**Comment by homanp** [comment]
Hey @adenta, 

The CSV file can be in any format, with any amount of data. Only requirement is that it is a valid CSV file. 

You can upload the CSV file via the UI but right now you won't be able to chat with it since we are migrating the document Q&A to `Python` here: https://github.com/homanp/langchain-ui-api/tree/main

It will be released today or tomorrow.
